#pragma once
#include "RHI/Public/RHI.h"
#include "Render/Public/RenderGraph.h"
#include "Core/Public/TArray.h"
#include "Math/Public/Math.h"

namespace Render {
	class HZBBuilder {
	public:
		HZBBuilder();
		~HZBBuilder() = default;
		void Update(uint32 srcWidth, uint32 srcHeight, const Math::FMatrix4x4& generatedByMatrix);
		RGTextureNode* BuildFurthest(RHITexture* depth, Render::RGTextureNode* depthNode, Render::RenderGraph& rg);
		RHITexture* GetTexture() { return m_HZB; }
		USize2D GetActualSize() const { return {m_ActualWidth, m_ActualHeight }; }
		const Math::FMatrix4x4& GetViewProjectMatrix() { return m_ViewProjectMatrix; }
	private:
		// hzb available size
		uint32 m_ActualWidth;
		uint32 m_ActualHeight;
		// hzb mip texture
		RHITexturePtr m_HZB;
		// hzb generated by tthis camera vp matrix
		Math::FMatrix4x4 m_ViewProjectMatrix;
		union HZBPSOFlags {
			uint32 Val;
			struct {
				bool Furthest : 1;
				bool Closest : 1;
				bool Output2x2 : 1;// if true, output 2x2 pixels per thread, else 1x1
			};
			HZBPSOFlags(): Val(0){}
		};
		TStaticArray<RHIComputePipelineStatePtr, 8> m_HZBPSOStorage;
		RHIComputePipelineStatePtr m_BlitPSO;
		RHIComputePipelineState* GetHZBPSO(HZBPSOFlags flags);
		void CreateBlitPSO();
		void CreateOutputTexture(uint32 dstSize);
	};
}